export const versiculosBiblicos = [
  "“O Senhor é o meu pastor; de nada terei falta.” — Salmos 23:1",
  "“Confie no Senhor de todo o seu coração e não se apoie em sua própria inteligência.” — Provérbios 3:5",
  "“Tudo posso naquele que me fortalece.” — Filipenses 4:13",
  "“Lâmpada para os meus pés é a tua palavra e luz para o meu caminho.” — Salmos 119:105",
  "“O Senhor te abençoe e te guarde.” — Números 6:24",
  "“Espere no Senhor. Seja forte e corajoso! Espere no Senhor.” — Salmos 27:14",
  "“O Senhor é a minha luz e a minha salvação; a quem temerei?” — Salmos 27:1",
  "“Deleite-se no Senhor, e ele atenderá aos desejos do seu coração.” — Salmos 37:4",
  "“O seu amor dura para sempre.” — Salmos 136:1",
  "“Reconheça o Senhor em todos os seus caminhos, e ele endireitará as suas veredas.” — Provérbios 3:6",
  "“O nome do Senhor é uma torre forte; os justos correm para ela e estão seguros.” — Provérbios 18:10",
  "“Ouve, ó Israel, o Senhor, o nosso Deus, o Senhor é um.” — Deuteronômio 6:4",
  "“Mil cairão ao seu lado, e dez mil à sua direita, mas você não será atingido.” — Salmos 91:7",
  "“O choro pode durar uma noite, mas a alegria vem pela manhã.” — Salmos 30:5",
  "“Lancem sobre ele toda a sua ansiedade, porque ele tem cuidado de vocês.” — 1 Pedro 5:7",
  "“Não temas, porque eu sou contigo; não te assombres, porque eu sou o teu Deus.” — Isaías 41:10",
  "“Ainda que eu ande pelo vale da sombra da morte, não temerei mal nenhum, pois tu estás comigo.” — Salmos 23:4",
  "“O Senhor é bom, uma fortaleza no dia da angústia; e conhece os que confiam nele.” — Naum 1:7",
  "“Busquem primeiro o Reino de Deus e a sua justiça, e todas essas coisas lhes serão acrescentadas.” — Mateus 6:33",
  "“Venham a mim, todos os que estão cansados e sobrecarregados, e eu darei descanso a vocês.” — Mateus 11:28",
  "“Porque Deus amou o mundo de tal maneira que deu o seu Filho unigênito...” — João 3:16",
  "“Eu sou a luz do mundo. Quem me segue nunca andará em trevas, mas terá a luz da vida.” — João 8:12",
  "“Deixo-lhes a paz; a minha paz lhes dou. Não a dou como o mundo a dá.” — João 14:27",
  "“Sabemos que todas as coisas cooperam para o bem daqueles que amam a Deus.” — Romanos 8:28",
  "“Se Deus é por nós, quem será contra nós?” — Romanos 8:31",
  "“Não se amoldem ao padrão deste mundo, mas transformem-se pela renovação da sua mente.” — Romanos 12:2",
  "“Não ajuntem tesouros na terra... mas ajuntem tesouros no céu.” — Mateus 6:19-20",
  "“O fruto do Espírito é amor, alegria, paz, paciência, amabilidade, bondade, fidelidade...” — Gálatas 5:22",
  "“Revistam-se de toda a armadura de Deus, para que possam permanecer firmes...” — Efésios 6:11",
  "“Não andem ansiosos por coisa alguma... apresentem os seus pedidos a Deus.” — Filipenses 4:6",
  "“Posso todas as coisas naquele que me fortalece.” — Filipenses 4:13",
  "“A fé é a certeza daquilo que esperamos e a prova das coisas que não vemos.” — Hebreus 11:1",
  "“Cheguem-se a Deus, e ele se chegará a vocês.” — Tiago 4:8",
  "“Eis que estou à porta e bato; se alguém ouvir a minha voz e abrir a porta, entrarei...” — Apocalipse 3:20",
  "“O Senhor guardará a tua entrada e a tua saída, desde agora e para sempre.” — Salmos 121:8",
  "“Tu, porém, permanece naquilo que aprendeste e de que foste inteirado, sabendo de quem o aprendeste.” — 2 Timóteo 3:14",
  "“Porque para Deus nada é impossível.” — Lucas 1:37",
  "“Bem-aventurados os que têm fome e sede de justiça, porque serão fartos.” — Mateus 5:6",
  "“Bem-aventurados os pacificadores, porque serão chamados filhos de Deus.” — Mateus 5:9",
  "“O Senhor firma os passos de um homem, quando a conduta deste o agrada.” — Salmos 37:23",
  "“Entrega o teu caminho ao Senhor; confia nele, e ele tudo fará.” — Salmos 37:5",
  "“Aquietai-vos e sabei que eu sou Deus.” — Salmos 46:10",
  "“Cria em mim, ó Deus, um coração puro e renova dentro de mim um espírito estável.” — Salmos 51:10",
  "“Este é o dia que o Senhor fez; regozijemo-nos e alegremo-nos nele.” — Salmos 118:24",
  "“As misericórdias do Senhor são a causa de não sermos consumidos, porque as suas misericórdias não têm fim.” — Lamentações 3:22",
  "“Grande é a tua fidelidade.” — Lamentações 3:23",
  "“Os que esperam no Senhor renovarão as suas forças; subirão com asas como águias.” — Isaías 40:31",
  "“Porque eu bem sei os pensamentos que tenho a vosso respeito, diz o Senhor, pensamentos de paz e não de mal.” — Jeremias 29:11",
  "“Antes de formá-lo no ventre eu o escolhi; antes de você nascer, eu o separei.” — Jeremias 1:5",
  "“Busquem o Senhor enquanto se pode achá-lo; invoquem-no enquanto está perto.” — Isaías 55:6",
  "“O Senhor pelejará por vocês; tão somente acalmem-se.” — Êxodo 14:14",
  "“Sede fortes e corajosos; não temais, porque o Senhor, vosso Deus, é quem vai convosco.” — Deuteronômio 31:6",
  "“Amem uns aos outros como eu os amei.” — João 13:34",
  "“Eu sou o caminho, a verdade e a vida. Ninguém vem ao Pai senão por mim.” — João 14:6",
  "“Permaneçam em mim, e eu permanecerei em vocês.” — João 15:4",
  "“Conhecereis a verdade, e a verdade vos libertará.” — João 8:32",
  "“O amor é paciente, o amor é bondoso.” — 1 Coríntios 13:4",
  "“Agora, pois, permanecem a fé, a esperança e o amor. O maior deles, porém, é o amor.” — 1 Coríntios 13:13",
  "“Se alguém está em Cristo, é nova criatura; as coisas antigas já passaram.” — 2 Coríntios 5:17",
  "“A minha graça te basta, porque o meu poder se aperfeiçoa na fraqueza.” — 2 Coríntios 12:9",
  "“Alegrem-se sempre no Senhor.” — Filipenses 4:4",
  "“A paz de Deus, que excede todo entendimento, guardará o coração e a mente de vocês.” — Filipenses 4:7",
  "“Em tudo deem graças.” — 1 Tessalonicenses 5:18",
  "“Toda a Escritura é inspirada por Deus e útil para o ensino.” — 2 Timóteo 3:16",
  "“Jesus Cristo é o mesmo ontem, hoje e para sempre.” — Hebreus 13:8",
  "“Sem fé é impossível agradar a Deus.” — Hebreus 11:6",
  "“Sejam praticantes da palavra, e não apenas ouvintes.” — Tiago 1:22",
  "“Resistam ao diabo, e ele fugirá de vocês.” — Tiago 4:7",
  "“Acima de tudo, tenham amor intenso uns pelos outros.” — 1 Pedro 4:8",
  "“Deus é amor.” — 1 João 4:8",
  "“No amor não há medo; ao contrário, o perfeito amor expulsa o medo.” — 1 João 4:18",
  "“Sê fiel até a morte, e dar-te-ei a coroa da vida.” — Apocalipse 2:10",
  "“E Deus enxugará dos seus olhos toda lágrima.” — Apocalipse 21:4",
  "“Lembra-te do dia de sábado, para o santificar.” — Êxodo 20:8",
  "“Seis dias trabalharás e farás toda a tua obra, mas o sétimo dia é o sábado dedicado ao Senhor, teu Deus.” — Êxodo 20:9-10",
  "“Porque em seis dias fez o Senhor os céus e a terra... e ao sétimo dia descansou; por isso o Senhor abençoou o dia de sábado e o santificou.” — Êxodo 20:11",
  "“Também lhes dei os meus sábados como sinal entre mim e eles, para que soubessem que eu sou o Senhor que os santifica.” — Ezequiel 20:12",
  "“Se desviares o teu pé de profanar o sábado... então te deleitarás no Senhor.” — Isaías 58:13-14",
  "“O sábado foi feito por causa do homem, e não o homem por causa do sábado.” — Marcos 2:27",
  "“Assim, o Filho do Homem é Senhor até mesmo do sábado.” — Marcos 2:28",
  "“Entrou Jesus, num sábado, na sinagoga, segundo o seu costume, e levantou-se para ler.” — Lucas 4:16",
  "“No sábado, saímos da cidade para a beira do rio, onde esperávamos encontrar um lugar de oração.” — Atos 16:13",
  "“Paulo, segundo o seu costume, foi procurá-los e, por três sábados, discutiu com eles com base nas Escrituras.” — Atos 17:2",
  "“Resta, portanto, um repouso sabático para o povo de Deus.” — Hebreus 4:9",
  "“Bem-aventurado o homem que guarda o sábado, não o profanando.” — Isaías 56:2",
  "“Felizes os que guardam os meus sábados e permanecem fiéis à minha aliança.” — Isaías 56:4",
  "“Santificai os meus sábados, pois servirão de sinal entre mim e vós.” — Ezequiel 20:20",
  "“De sábado em sábado virá toda a humanidade adorar perante mim, diz o Senhor.” — Isaías 66:23",
];